### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by NostalgiaRunner** [benkimo6i/vanilla-js-carousel#3]
Hello! I recently found this repo linked on a site and think this is a really awesome carousel! The site I found it on listed the license as MIT, but I didn't see that mentioned anywhere here, nor a license in general. I didn't want to step on any toes, so I wanted to ask about it. If you have no preference on a type of license, would you be willing to license this under the MIT license?

Thank you for your time and effort,
NR

**Comment by benkimo6i** [comment]
Done! thanks for reaching out and for the heads up
