### ISSUE TITLE
How to Auto Play?

### ISSUE THREAD

**Issue by innocentrixphilippines** [benkimo6i/vanilla-js-carousel#4]
How to Auto Play?

**Comment by benkimo6i** [comment]
Great suggestion, I will add this to my list of updates for vanilla-js-carousel v2 release 

`setCurrentState(direction)` is the main function that controls the direction the gallery should move. The way I would approach an autoplay feature: I would use a `setInterval` function and for its parameters call the `setCurrentState(direction)` function and set an interval value for every time I want the gallery to move.

```i.e.
setInterval(setCurrentState('gallery-controls-next'), 500);
```

so what this should do is run the main function that moves the gallery every 500 milliseconds - the `direction` value is either `gallery-controls-next` or `gallery-controls-previous`, in the code we see that these values are the classnames of the buttons

**Comment by Hewsta** [comment]
Where does this function go in the code?

**Comment by benkimo6i** [comment]
@Hewsta @innocentrixphilippines Hey thanks for your patience, so I've added a new play() method to the carousel! I have also made some important refactors to the carousel to simplify things so be sure to checkout the [PR](https://github.com/benkimo6i/vanilla-js-carousel/pull/6) that was merged before moving forward.

So to autoplay your carousel, after your carousel mounts, adding a play method to your carousel object should get it to autoplay, see example code below: 
```
// The carousel element you want to target
const el = document.querySelector('.carousel');
// Create a new carousel object
const yourCarousel = new Carousel(el);
// Setup carousel and methods
yourCarousel.mounted();
// Initiate autoplay
yourCarousel.play()
```
